version: '3.8'

services:

  node:
    image: node:alpine
    working_dir: /user/src/app
    volumes:
      - ./app:/user/src/app
    ports:
        - "3000:3000"
    command: sh -c "npm install && npm run start"

  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - ./postgres:/var/lib/postgresql/data